batch_size: 16
workers: 8
nepoch: 400

model_name: PointAttN_baseline_cd_matching_f1_MC

# model_name: PointAttN_baseline_cd_matching_f1


# python train_not_noisy.py -c PointAttN.yaml
# python test_pcn_MC.py -c PointAttN.yaml 


load_model:
# load_model: ./log/PointAttN_baseline_cd_matching_f1_MC_cd_debug_pcn/best_cd_p_coarse_network.pth   
# load_model: ./log/PointAttN_baseline_cd_matching_f1_MC_cd_debug_pcn/best_cd_p_network.pth   
# load_model: ./log/PointAttN_baseline_cd_matching_f1_MC_cd_debug_pcn/best_cd_t_coarse_network.pth   
# load_model: ./log/PointAttN_baseline_cd_matching_f1_MC_cd_debug_pcn/best_cd_t_network.pth   
# load_model: ./log/PointAttN_baseline_cd_matching_f1_MC_cd_debug_pcn/best_f1_network.pth   
# load_model: ./log/PointAttN_baseline_cd_matching_f1_MC_cd_debug_pcn/network.pth 
# load_model: ./log/PointAttN_baseline_cd_matching_f1_MC_cd_debug_pcn/network.pth 

# load_model: ./log/PointAttN_baseline_cd_matching_f1_no_occ_cd_debug_pcn/best_cd_t_coarse_network.pth   


start_epoch: 0
num_points: 2048
work_dir: log/
flag: debug
loss: cd 
manual_seed: 1748
step_interval_to_print: 100
epoch_interval_to_save: 1
epoch_interval_to_val: 1

lr: 0.0001
lr_decay: True
lr_decay_interval: 40
lr_decay_rate: 0.7
lr_step_decay_epochs: null
lr_step_decay_rates: null
lr_clip: 1.e-6
optimizer: Adam
weight_decay: 0
betas: 0.9, 0.999

device: '0'
dataset: 'pcn'
pcnpath: $PATH/ShapeNetCompletion
c3dpath: $PATH/shapenet
# test
save_vis: True
